//-----------------------------------------------------------------------------
// Colorize MultimediaLib
// Copyright 2009-2024 Colorize
// Apache license (http://www.apache.org/licenses/LICENSE-2.0)
//-----------------------------------------------------------------------------

package nl.colorize.multimedialib.scene.effect;

import nl.colorize.multimedialib.mock.MockImage;
import nl.colorize.multimedialib.renderer.headless.HeadlessRenderer;
import nl.colorize.multimedialib.stage.ColorRGB;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class ParticleWipeTest {

    @Test
    void renderParticles() {
        HeadlessRenderer renderer = new HeadlessRenderer();
        renderer.start(new ParticleWipe(new MockImage(), ColorRGB.RED, 10f, false), null);
        renderer.doFrame();
        renderer.doFrame();

        String expected = """
            Stage
                Container [$$root, 1]
                    Container [154]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
                        Sprite [$$default]
            """;

        assertEquals(expected, renderer.getContext().getStage().toString());
    }
}
