name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    container: colorizenl/colorize-ci
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compile
        run: gradle compileJava
      - name: Unit tests
        run: gradle -Djava.awt.headless=true coverage --info
      - name: Transpile TeaVM demo applications
        run: gradle npmInstall transpileDemoApplication2D transpileDemoApplication3D
    env:
      ORG_GRADLE_PROJECT_githubPackagesOwner: "colorizenl"
      ORG_GRADLE_PROJECT_githubPackagesToken: "${{ secrets.TEAVM_PACKAGES_TOKEN }}"
